spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept
server:
  port: 8200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: provider-dept8200
---
spring:
  profiles: test
  application:
    name: springcloud-provider-test
server:
  port: 8300
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: provider-dept8300